### ISSUE TITLE
Milestone 1 Tasks Allocation

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/525_group11#1]
**TASKS:**

 - [x] Teamwork contract **(Rachel)**
 - [x] Repo & Project structure (Rachel)
 - [x] README.md **(Rachel)**
 - [x] Download Data **(Mai)**
 - [x] Combine data CSVs **(Mai)**
 - [x] Load combined csv to memory and perform simple EDA & Discussions **(Saule & Rachel)**
       - [ ] Changing dtype of your data **(Saule)**
       - [ ] Load just columns what we want **(Saule)**
       - [ ] Loading in chunks **(Rachel)**
       - [ ] Dask **(Rachel)**
 - [x] Perform EDA in R & Discussion **(Vu)**
        - [ ] Pick an approach to transfer the dataframe from python to R
        - [ ] Discuss why you chose this approach over others

**REVIEWER ALLOCATION**

- [x] Rachel reviews Mai’s
- [x] Mai reviews Saule’s
- [x] Saule reviews Vu’s
- [x] Vu reviews Rachel’s

**CANVAS SUBMISSION:**
- [x] URL of your public project’s repo
- [x] URL of your notebook for this milestone
- [x] URL to teamwork contract

**Comment by rainbowxyt0305** [comment]
Done!
